# Basics of probability

Statistics is the study of uncertainty. How do we measure uncertainty? Typically we deal with uncertainty by means of probabilities [@Kruschke2015DBDA]. But what are then probabilities?

There are roughly three different frameworks to define probabilities: the **classical** framework, the **frequentist** framework, and the **Bayesian** framework.

In general, a probability, under any of these frameworks, is just a way of assigning numbers to a set of mutually exclusive possibilities. The numbers, called "_probabilities_", just need to satisfy three properties [@Kolmogorov2018ProbTheory]:

1. A probability value must be non-negative (i.e., greater than or equal to zero).
2. The sum of the probabilities across all events in the sample space must be 1.0
3. For any two mutually exclusive events, the probability that one or the other occurs is the sum of their individual probabilities.

Under the classical framework, outcomes that are equally likely have equal probabilities. For example, when rolling a fair die, there are six possible outcomes, and they're all equally likely, thus the probability of rolling a four is just $\mbox{Pr}(X = 4) = \frac{1}{6}$. 

Under the frequentist framework, probabilities are regarded to as long-run relative frequencies.

```{python}
#| label: fig-rolling-dice
#| fig-cap: The long-run relative frequency of rolling a 4 with a fair six-sided die.
import numpy as np
import matplotlib.pyplot as plt

N = 4_000  # number of rolls
xs = np.random.choice(a=6, size=N, replace=True, p=np.ones(6)/6)

fig, ax = plt.subplots()
ax.plot(
    np.arange(1, N + 1),
    [np.mean(xs[:roll] == 3) for roll in np.arange(1, N + 1)]
)
ax.axhline(1./6, c="gray", ls="-.", label=f"1/6")
ax.set_xlabel("Number of rolls")
ax.set_ylabel(f"Pr($X$=4)")
plt.tight_layout()
plt.show()
```

## Random variables
Suppose that $X$ represents some unknown quantity of interest. If the value of $X$ is unknown, or could change, we call it a **random variable**. The set of possible values, denoted $\mathcal{X}$, is called the **sample space**. An **event** is a set of outcomes from a given sample space [@Murphy2022Introduction].

::: {.callout-tip}
## Example: random variables

If $X$ represents the face of a dice that is rolled, i.e., $\mathcal{X} = \left\{1, 2, \ldots, 6 \right\}$, the event of "_seeing a 1_" is denoted $X = 1$, the event of "_seeing an odd number_" is $X \in \left\{1, 3, 5 \right\}$.
:::

### Events
The expression $\mbox{Pr}(A)$ is used to denote the probability with which you believe an event $A$ is true. If an event will definitely happen, we write $\mbox{Pr}(A)=1$ and if an event is definitely not happening we write $\mbox{Pr}(A)=0$. Furthermore, the probability of $A$ not happening is denoted $\mbox{Pr}(\bar{A}) = 1 - \mbox{Pr}(A)$.